source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'

target 'FPRefresh_Example' do
  pod 'FPRefresh', :path => '../'

  target 'FPRefresh_Tests' do
    inherit! :search_paths

    
  end
end
